CREATE TABLE note (
  NOTE_ID INT NOT NULL AUTO_INCREMENT,
  NOTE_NAME VARCHAR(45) NOT NULL,
  NOTE_DATE DATE NOT NULL,
  NOTE_BODY MEDIUMTEXT NULL,
  USER_ID INT(11) NOT NULL,
  PRIMARY KEY (NOTE_ID));
